export  enum navEnum  {
  dashboard = 'dashboard',
  portageBill = 'portage-bill',
  accessRights = 'access-rights',
  VendorReport = 'VendorReport',
  NewApplicant = 'NewApplicant',
  CrewDetails = 'CrewDetails',
  PendingApprovals = 'PendingApprovals',
  InActiveList = 'InActiveList',
  NTBRList = 'NTBRList',
  documentDetails = 'document-details',
  readDocuments = 'read-documents',
  AuthorityCorrespondanceList = 'AuthorityCorrespondanceList',
  pniReports = 'pni-reports',  
  crewChangeHistory = 'crew-change-history',
  activityLogs = 'activity-logs',
  pageHelp = 'page-help',
  checkDocument = 'doc-status',
  manualRights = 'manual-rights',
  maskedList='MaskedList',
  accountReports = 'pni-reports',  
  SWFSrate = 'SWFSrate',
}
export  enum crewDetailsNavEnum  {
    Particulars = 'Particulars',
    crewAddress = 'crewAddress',
    CrewBankdetail = 'CrewBankdetail',
    crewFamily = 'crewFamily',
    crewQualification = 'crewQualification',
    crewLicense = 'crewLicense',
    crewCourses = 'crewCourses',
    crewOtherdocument = 'crewOtherdocument',
    offerletter='offerletter',
    crewTraveldocuments = 'crewTraveldocuments',
    crewAccounthistory = 'crewAccounthistory',
    crewMedicalHistory = 'crewMedicalHistory',
    crewPI = 'crewPI',
    crewSea = 'crewSea',
    crewImpNote = 'crewImpNote',
    crewnote = 'crewnote',
    crewMail = 'crewMail',    
    Grievance = 'Grievance',
    Appraisal = 'Appraisal',
    MedicalCorrespondence = 'medical-correspondence',
    crewApproval = 'crewApproval',
    crewComplaint = 'crewComplaint',
    bonus = 'bonus',
  }
  export enum seafarerNavEnum {
    RankRegister = 'RankRegister',
    License = 'License',
    CourseRegister = 'CourseRegister',
    QualificationRegister = 'QualificationRegister',
    authority = 'authority',
    InjurySubType = 'InjurySubType',
    OtherDocuments = 'OtherDocuments',
    CorrespondenceType = 'CorrespondenceType',
    RemarkType = 'RemarkType',
    piGroup = 'piGroup',
    Pool = 'Pool',
    AddZonal = 'AddZonal',
    appraisalType = 'appraisal-type',
    CourseCost = 'course-cost',
  }
  export enum shipNavEnum {
    VesselRegister = 'VesselRegister',
    OwnerRegister = 'OwnerRegister',
    ManagerRegister = 'ManagerRegister',
    PrincipalRegister = 'PrincipalRegister',
    DisponentRegister = 'DisponentRegister',
    EngineModel = 'EngineModel',
    EngineType = 'EngineType',
    EngineSubType = 'EngineSubType',
    ShipType = 'ShipType',
    Certificate = 'Certificate',
    AddMTUnion = 'AddMTUnion',
    Correspondence = 'Correspondence',
    vesselCertificateMatrix = 'vessel-certificate-matrix',
    VesselChange = 'vessel-change',
    ecdis = 'ecdis',
    CompCourseMat = 'comp-course-mat',
    EngineMaker = 'EngineMaker',
  }
  export enum travelNavEnum {
    country = 'Country',
    State = 'State',
    City = 'City',
    Airport = 'Airport',
    Seaport = 'Seaport', 
    visaRequirement = 'visa-requirement',
  }
  export enum accountNavEnum {
    CbaUnion = 'CbaUnion',
    WageComponent = 'WageComponent',
    BudgetCode = 'BudgetCode',
    BudgetSubCode = 'BudgetSubCode',
    wagestructure = 'wagestructure',
    cba = 'cba',
    copystructure = 'copy-wage',
    conversionrate = 'conversionrate',
    SWFSrate = 'SWFSrate',
    pfrate = 'pfrate',
    nusirate = 'nusirate',
    accountcodemapping = 'accountcodemapping',
  }
  export enum vendorNavEnum {
    AddServiceGroup = 'AddServiceGroup',
    AddService = 'AddService',
    VendorRegister = 'VendorRegister',
    Charterer = 'Charterer',
    Builders = 'Builders',
    Classification = 'Classification',
    Institutes = 'Institutes',
    VendorQuotation = 'VendorQuotation',
    ServiceItem = 'ServiceItem',
    VendorReport='VendorReport'
  }
  export enum reasonNavEnum {
    ReasonNTBR = 'ReasonNTBR',
    ReasonInActive = 'ReasonInActive',
    ReasonReEmpCategory = 'ReasonReEmpCategory',
    ReasonReEmpSubCategory = 'ReasonReEmpSubCategory',
    ReasonReEmpReason = 'ReasonReEmpReason',
    ReasonTravel = 'ReasonTravel',
    ReasonPortCall = 'ReasonPortCall',
    ReasonOT = 'ReasonOT',
    ReasonOTLimit = 'ReasonOTLimit',
    ReasonSignOff = 'ReasonSignOff',
    ReasonSignOn = 'ReasonSignOn',
    ReasonIllness = 'ReasonIllness',
    ReasonExtraCrew = 'ReasonExtraCrew',
    ReasonDelayed = 'ReasonDelayed',
  }
  export enum manningReportsEnum {
    crewChangeHistory = 'crew-change-history',
    crewChangePlan = 'crew-change-plan',
    crewDocsStatus = 'crew-docs-status',
    extraCrewReport = 'extra-crew-report',
    appraisalReport = 'appraisal-report',
    importantReport = 'important-report',
    grievanceReport = 'grievance-report',
    vesselDocsStatus = 'vessel-docs-status',
    vesselDetailReport = 'vessel-detail-report',
    vesselCommReport = 'vessel-comm-report',
    vesselMgmtReport = 'vessel-mgmt-report',
    retentionrate = 'retentionrate',
    bmi = 'bmi',
    crewDocExpiry = 'crew-doc-expiry',
    crewDOA = 'crew-doa',
    waiver = 'waiver',
    recruitment = 'recruitment',
    reliefData = 'relief-data',
    promotion = 'promotion',
    preJoiningFitness = 'prejoining-fitness',
    appreciation = 'appreciation',
    dce = 'dce',
    overDueData = 'overdue-data',
    returnee = 'returnee',
    crewPlan = 'crew-plan',
    crewChange = 'crew-change',
    onboardMatrix = 'onboard-matrix',
    licenseSearch='licenseSearch',
    rankExpSearch='rankExpSearch',
    opExpSearch='opExpSearch',    
    extracrewwageReport = 'extra-crew-wage-report',
    appraisalSummary = 'appraisal-summary',
    calling = 'calling-report',
    medicalSignoff='medical-signoff',
    seafarerEntry='seafarerEntry',
    stepwaiverreq='stepwaiverreq',
  }
  export enum vesselNavEnum {
    crewlist = 'crewlist',
    crewlistHistory = 'crewlist-history',
    vesselParticular = 'vessel-particular',
    vesselCertificate = 'vessel-certificate',
    safeManning = 'safe-manning',
    vesselMatrix = 'vessel-matrix',
    vesselCourseMatrix = 'vessel-course-matrix',  
    VesselVoyageHistory = 'VesselVoyageHistory',
    VesselCBA = 'VesselCBA',
    VesselCorrespondance = 'VesselCorrespondance',
    VesselActivity = 'vessel-activity',
    checklistMatrix = 'checklist-docs',  
    workgear='workgear' ,
    flagRequest='flagRequest' ,
    cabotage = 'cabotage',
  }
  export enum payrollNavEnum {
    portagebill = 'portage-bill', 
    holdlist = 'hold-list',   
    unlockportagebill = 'unlock-portage-bill', 
    mastercash = 'master-cash',   
    unlockmastercash = 'unlock-master-cash', 
    bankallotment = 'bankallotment',   
    payslipreport = 'payslipreport',
    extracrewwagereport = 'extracrewwagereport',
    transferreport = 'transfer-report',
    midmonthallotment = 'midmonthallotment',
    holdwageslist = 'holdwageslist',    
  }

  export enum pniNavEnum {
    pnireports = 'pni-reports', 
    pniclaim = 'pni-claim',
  }
  export enum accountsreportNavEnum {
    swfsReport = 'swfsreport', 
    pfReport = 'pfReport',
    nusireport = 'nusireport',
    insurance = 'insurance',
  }